### ISSUE TITLE
Fractional point doesn't work

### ISSUE THREAD

**Issue by SMSourov** [rajput-hemant/calculator#72]
**Description:**
In some calculations, the fractional point doesn't work at all. This was the first time where a calculator app failed to work properly for me.

**Steps to reproduce the problem:**
1. Install and open the app.
2. Try to make this calculation "4.6+2.4"

**Expected behaviour:**
"4.6+2.4" should appear and its calculation("7") in a small area.

**Current behaviour:**
"4.6+24" should appear and its calculation("28.6") in a small area.

**Comment by Ao1Pointblank** [comment]
This issue still exists (v1.0.0)

**Comment by SMSourov** [comment]
> This issue still exists (v1.0.0)

Can you tell the steps to reproduce?

**Comment by Ao1Pointblank** [comment]
Try multiplying 19.5*3.5
The second decimal will not type out

I am using android 13 Graphene OS on a pixel 5

**Comment by rajput-hemant** [comment]
@Ao1Pointblank I recommend downloading the most recent version of the application from [this link](https://github.com/rajput-hemant/calculator/releases), as the issue you mentioned has been resolved in [v0.2.2](https://github.com/rajput-hemant/calculator/releases/tag/v0.2.2). The fix was implemented in the following commit: https://github.com/rajput-hemant/calculator/commit/e2ed28700f72540dc57e593b186c8a4a3dfaa1f3

**Comment by Ao1Pointblank** [comment]
thanks!
i got the app from f-droid, i assume you are not maintaining it there?
